# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing Cypress
      run: npm ci
      
    - name: Installing Mocha
      run: npm i mocha
      
    - name: Run build if present
      run: npm run build --if-present
    
    - name: Run Cypress tests
      run: npm run scripts
      
    - name: Copy test execution videos and screenshots
      run: |
          mkdir public
          cp -r cypress/videos public/videos
          
    - name: Merge test reports
      run: npm run combine-reports

    - name: Generate HTML report
      run: npm run generate-report
      
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
